name: Feature Request
description: Request a new feature for an existing presence
labels: [feature request, presence]
body:
  - type: markdown
    attributes:
      value: |
        Before requesting a new feature, ensure your request hasn't already been
        submitted before. If it has, reply to the open issue instead.
  - type: input
    attributes:
      label: Presence name
    validations:
      required: true
  - type: textarea
    validations:
      required: true
    attributes:
      label: Description
      description: Describe in detail what would you like to see added to the presence and why.
